# Numpy Tutorials

In [1]:
import numpy as np

In [2]:
# 1-D array
a = np.array([1,2,3])
print(a,type(a),a.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)


In [3]:
# 2-D array
b = np.array([[1,2,3],[4,5,6]])
print(b,type(b),b.shape,b[0,0])

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3) 1


In [4]:
# In built functions of array creation
z = np.zeros((2,3)) # Shape as param
print(z,type(z),z.shape,z[0,0])

[[ 0.  0.  0.]
 [ 0.  0.  0.]] <class 'numpy.ndarray'> (2, 3) 0.0


In [5]:
# Array of Ones
o = np.ones((2,3)) # Shape as param
print(o,o.shape,type(o),o[0,1])

[[ 1.  1.  1.]
 [ 1.  1.  1.]] (2, 3) <class 'numpy.ndarray'> 1.0


In [6]:
# Constant array
c = np.full(shape=(4,4),fill_value=7)
print(c,c.shape,type(c),c[3,3])

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] (4, 4) <class 'numpy.ndarray'> 7


In [7]:
# Identity Matrix
i = np.eye(N=3) # As identity matrix is always a square matrix
print(i,i.shape)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] (3, 3)


In [8]:
# Random Matrix
r = np.random.random(size=(2,2))
print(r,r.shape)

[[ 0.14265966  0.63623475]
 [ 0.8012621   0.83813729]] (2, 2)


## Array Slicing
Array slicing in numpy is very easy and we just have to consider multiple arrays as singular dimensions but there's a catch

### Array slicing creates a reference to the original array, hence, any changes made to the new array will transform the original array as well

In [9]:
# Array Slicing
sliced_array = c[:3,1:]
sliced_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
sliced_array[0,0] = 99

print("Current array:- \n",sliced_array)
print("Original array:- \n",c)

Current array:- 
 [[99  7  7]
 [ 7  7  7]
 [ 7  7  7]]
Original array:- 
 [[ 7 99  7  7]
 [ 7  7  7  7]
 [ 7  7  7  7]
 [ 7  7  7  7]]


In [11]:
# Accessing data in middle row keeping multidimensionality
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:- \n",a)

# Viewing Middle Row
# Integer Slicing
r = a[1,:]
print("Integer Slicing \n",r,r.shape)

# Index Slicing
r = a[[1],:]
print("Index Slicing 1 \n",r,r.shape)

r = a[1:2,:]
print("Index Slicing 2 \n",r,r.shape)


Original Array:- 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Integer Slicing 
 [5 6 7 8] (4,)
Index Slicing 1 
 [[5 6 7 8]] (1, 4)
Index Slicing 2 
 [[5 6 7 8]] (1, 4)


Same can be done for Columns

#### Integer Array Indexing
Integer array indexing allows us to construct arbitrary arrays using data from another array.

In [12]:
a = np.array([[1,2],[3,4],[5,6]])

# Integer array indexing
# Shape:- (3,)
print(a[[0,1,2],[0,1,0]])

# Another way
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]
[1 4 5]


In [13]:
# Integer array indexing uses include mutating each element from each row of a matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# Array of indices
b = np.array([0,2,0,1])

# Selecting one from each row
a[np.arange(4),b]

array([ 1,  6,  7, 11])

In [14]:
a[np.arange(4),b] += 10
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

#### Boolean array Indexing

In [15]:
# Finds the elements of a > 2
bool_idx = (a>2) 
bool_idx

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [16]:
a[bool_idx]

array([11,  3,  4,  5, 16, 17,  8,  9, 10, 21, 12])

## DataTypes

In [17]:
X = np.array([1,2,3]) # Numpy chooses the dtype
y = np.array([1.0,2.0]) # Numpy chooses the dtype
z = np.array([1,2], dtype=np.int64) # We choose it

print(X.dtype,y.dtype,z.dtype)

int64 float64 int64


## MATHS IN NUMPY
Numpy overloads basic mathematical operatives as shown below

In [18]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise Sum
print("\nElementwise Sum\n")
print(x+y)
print(np.add(x,y))
# Elementwise difference
print("\nElementwise difference\n")
print(x-y)
print(np.subtract(x,y))
# Elementwise division
print("\nElementwise division\n")
print(x/y)
print(np.divide(x,y))
# Elementwise multiplication
print("\nElementwise multiplication\n")
print(x*y)
print(np.multiply(x,y))
# Elementwise square root
print("\nElementwise square root\n")
print(np.sqrt(x))


Elementwise Sum

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]

Elementwise difference

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

Elementwise division

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]

Elementwise multiplication

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]

Elementwise square root

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [19]:
# Dot product is used for vector scalar multiplication
print(np.dot(x,y))
print(x.dot(y))

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [20]:
# Some inbuilt functions of numpy
print(np.sum(x)) # Computes sum of all elements of x
print(np.sum(x, axis=0)) # Computes sum of each column
print(np.sum(x, axis=1)) # Computes sum of each row

10.0
[ 4.  6.]
[ 3.  7.]


#### Manipulation of vector shapes, transformations, etc

In [21]:
print(x)
print("Transpose:- \n",x.T)

[[ 1.  2.]
 [ 3.  4.]]
Transpose:- 
 [[ 1.  3.]
 [ 2.  4.]]


## Broadcasting:- Working With Arrays of Different Shapes

#### We want to add a constant vector to each row of a matrix

In [22]:
# METHOD 1:-
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # Creates an array of same as x

# Adding vector using a loop
for i in range(0,4):
    y[i:] = x[i:] + v
    
# Pretty poor method :(
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [23]:
# METHOD 2:-
# We can make an array of shape of x and each row  = v and then add them
vv = np.tile(v,(4,1))
print(vv)

y = vv+x
# Boring again af
y

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [24]:
# Using Broadcasting, Simple af
y = x+v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

### Rules for broadcasting
Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

3. The arrays can be broadcast together if they are compatible in all dimensions.

4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [25]:
v = np.array([1,2,3])
w = np.array([4,5])

np.reshape(v, (3,1)) * w # Broadcasting

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [26]:
x = np.array([[1,2,3],[4,5,6]])
x + v

array([[2, 4, 6],
       [5, 7, 9]])

In [27]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [28]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [29]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])